version: '3.1'

services:
  db:
    image: mysql
    restart: always
    ports:
      - '3308:3306'
    environment:
      MYSQL_DATABASE: cloud_vendor
      MYSQL_USER: spring
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root

